### ISSUE TITLE
Upgrade to Angular v15

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/ngx-trebol-frontend#139]
## Must read

- https://github.com/angular/angular/blob/15.0.x/CHANGELOG.md
- https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8

## Additional notes

- Karma is being deprecated in favor of Jest.

**Comment by nazislam** [comment]
Hey, I have done similar type of work in a freelancing site. I wish to work on this angular update task. Can you please make sure I'm assigned for this item? Thanks.

**Comment by bglamadrid** [comment]
> Hey, I have done similar type of work in a freelancing site. I wish to work on this angular update task. Can you please make sure I'm assigned for this item? Thanks.

Hey, thank you, that's great! I think this just might be a little heavy or little messy task, so please ask away if you have any questions during your process ;)

**Comment by nazislam** [comment]
Sure, will reach out if I have any concerns. Thanks!
