### ISSUE TITLE
Example datasets for local memory module

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/ngx-trebol-frontend#17]
A few more examples of data in the `src/app/data/local-memory` services wouldn't hurt.

**Comment by dmodena** [comment]
Hi, I would like to work on this issue.

**Comment by dmodena** [comment]
I just created a PR #23 for this issue

**Comment by bglamadrid** [comment]
@dmodena I approved and merged your changes. Many thanks! The issue still remains for other entities.
