### ISSUE TITLE
Stick footer to the bottom of the page, not the screen

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/ngx-trebol-frontend#80]
I didn't test this correctly before, but I realized the footer takes up too much space, being stuck to the bottom of the screen instead of the bottom of the page.

I believe it should be fixable by changing the template of the `StoreComponent`. It uses flexbox layout btw.

**Comment by tcvan0707** [comment]
Please take a look at my pull request and approve it if it is possible. Thank you.

**Comment by tcvan0707** [comment]
> > Hello, can i work on this issue? I want to give it a try.
> 
> Sure thing! I'm assigning it to you. Don't hesitate to ask if you have any questions.

Could you please review my PR as soon as possible?
